"""Generate the governed STEP 03 notebooks as thin consumers of source logic."""

from __future__ import annotations

from pathlib import Path

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook


def _metadata() -> dict[str, object]:
    return {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "version": "3.11"},
    }


def build_eda_notebook() -> nbformat.NotebookNode:
    """Build the required EDA notebook without notebook-only transformations."""
    cells = [
        new_markdown_cell(
            "# Vantara — 01 EDA\n\n"
            "This notebook is an auditable consumer of reusable `src/` logic. "
            "It does not own production transformations. All displayed tables and figures "
            "are generated by `src.analysis.eda` from governed STEP 02 artifacts."
        ),
        new_code_cell(
            "import sys\n"
            "from pathlib import Path\n\n"
            "import pandas as pd\n"
            "from IPython.display import Image, Markdown, display\n\n"
            "ROOT = Path.cwd()\n"
            "if ROOT.name == 'notebooks':\n"
            "    ROOT = ROOT.parent\n"
            "sys.path.insert(0, str(ROOT))\n\n"
            "from src.analysis.eda import run_step03_analysis  # noqa: E402\n\n"
            "summary = run_step03_analysis(ROOT / 'config/config.yaml', project_root=ROOT)\n"
            "summary"
        ),
        new_markdown_cell("## Spend, frequency, and recency"),
        new_code_cell(
            "eda_dir = ROOT / 'reports/eda'\n"
            "rfm = pd.read_csv(eda_dir / 'rfm_summary.csv')\n"
            "comparison = pd.read_csv(eda_dir / 'churn_rfm_comparison.csv')\n"
            "display(rfm)\n"
            "display(comparison)\n"
            "display(Image(filename=str(eda_dir / 'rfm_distributions.png')))"
        ),
        new_markdown_cell("## Churn target balance"),
        new_code_cell(
            "display(pd.read_csv(eda_dir / 'class_balance.csv'))\n"
            "display(Image(filename=str(eda_dir / 'churn_class_balance.png')))"
        ),
        new_markdown_cell("## Country analysis"),
        new_code_cell(
            "display(pd.read_csv(eda_dir / 'country_summary.csv'))\n"
            "display(Image(filename=str(eda_dir / 'country_revenue.png')))"
        ),
        new_markdown_cell("## Seasonality"),
        new_code_cell(
            "display(pd.read_csv(eda_dir / 'seasonality_summary.csv'))\n"
            "display(Image(filename=str(eda_dir / 'monthly_orders.png')))"
        ),
        new_markdown_cell("## Outlier and data-quality review"),
        new_code_cell("display(pd.read_csv(eda_dir / 'outlier_summary.csv'))"),
        new_markdown_cell("## Written modeling hypotheses"),
        new_code_cell("display(Markdown((eda_dir / 'hypotheses.md').read_text(encoding='utf-8')))"),
    ]
    return new_notebook(cells=cells, metadata=_metadata())


def build_feature_notebook() -> nbformat.NotebookNode:
    """Build the required feature-engineering/data-freeze evidence notebook."""
    cells = [
        new_markdown_cell(
            "# Vantara — 02 Feature Engineering and Data Freeze\n\n"
            "This notebook consumes the canonical STEP 02 feature table and STEP 03 schema "
            "evidence. Feature construction, leakage controls, correlation, VIF, and schema "
            "selection all live in reusable `src/` modules."
        ),
        new_code_cell(
            "import json\n"
            "import sys\n"
            "from pathlib import Path\n\n"
            "import pandas as pd\n"
            "from IPython.display import Image, display\n\n"
            "ROOT = Path.cwd()\n"
            "if ROOT.name == 'notebooks':\n"
            "    ROOT = ROOT.parent\n"
            "sys.path.insert(0, str(ROOT))\n\n"
            "from src.analysis.eda import run_step03_analysis  # noqa: E402\n\n"
            "summary = run_step03_analysis(ROOT / 'config/config.yaml', project_root=ROOT)\n"
            "features = pd.read_parquet(ROOT / 'data/processed/customer_features_churn.parquet')\n"
            "schema_path = ROOT / 'models_artifacts/churn_feature_schema.json'\n"
            "schema = json.loads(schema_path.read_text())\n"
            "{'feature_table_shape': features.shape, 'freeze_summary': summary}"
        ),
        new_markdown_cell("## Complete governed feature table"),
        new_code_cell(
            "excluded_columns = {\n"
            "    'customer_id',\n"
            "    'cutoff_timestamp',\n"
            "    'churn',\n"
            "    'partition',\n"
            "    'split_version',\n"
            "}\n"
            "feature_columns = [c for c in features.columns if c not in excluded_columns]\n"
            "affinity_columns = [\n"
            "    c for c in feature_columns if c.startswith('category_affinity_')\n"
            "]\n"
            "display(pd.DataFrame({'feature': feature_columns}))\n"
            "{'complete_features': len(feature_columns), "
            "'affinity_features': len(affinity_columns)}"
        ),
        new_markdown_cell("## Training-only correlation evidence"),
        new_code_cell(
            "freeze_dir = ROOT / 'reports/data_freeze'\n"
            "display(pd.read_csv(freeze_dir / 'high_correlation_pairs.csv'))\n"
            "display(Image(filename=str(ROOT / 'reports/eda/selected_feature_correlation.png')))"
        ),
        new_markdown_cell("## VIF evidence before and after selection"),
        new_code_cell(
            "display(pd.read_csv(freeze_dir / 'vif_initial.csv').head(20))\n"
            "display(pd.read_csv(freeze_dir / 'vif_final.csv').head(20))"
        ),
        new_markdown_cell("## Frozen churn model feature order"),
        new_code_cell(
            "display(pd.DataFrame({'selected_feature': schema['selected_features']}))\n"
            "exclusions = [\n"
            "    {'excluded_feature': key, 'reason': value}\n"
            "    for key, value in schema['exclusions'].items()\n"
            "]\n"
            "display(pd.DataFrame(exclusions))\n"
            "{'schema_version': schema['schema_version'], 'feature_count': schema['feature_count']}"
        ),
        new_markdown_cell(
            "## Data-freeze decision\n\n"
            "The complete business feature table is preserved. The frozen model schema removes "
            "only a reference affinity category, exact/redundant monetary relationships, "
            "zero-variance inputs, or features exceeding the configured training-only VIF gate. "
            "All six classical churn models and the ANN must consume this exact versioned order."
        ),
    ]
    return new_notebook(cells=cells, metadata=_metadata())


def main() -> int:
    """Write both canonical STEP 03 notebook files."""
    notebook_directory = Path("notebooks")
    notebook_directory.mkdir(parents=True, exist_ok=True)
    nbformat.write(build_eda_notebook(), notebook_directory / "01_eda.ipynb")
    nbformat.write(build_feature_notebook(), notebook_directory / "02_feature_engineering.ipynb")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
